spring:

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  redis:
    host: localhost
    port: 6379

resilience4j:

  retry:
    instances:
      availabilityRetry:
        max-attempts: 3
        wait-duration: 500ms

  circuitbreaker:
    instances:
      availabilityCB:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
